import { NextResponse } from "next/server";
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error'],
});
export async function GET() {
   try{
    const result = await prisma.imei_user_junction.findMany({
      select: {
        SEQ_NUM: true,
        USER_SEQ_NUM: true,
        INFO_SEQ_NUM: true,
        INFO_D_SEQ_NUM: true,
        SERVICE_NO: true,
        SERVICE_FEE: true,
        SEARCH_DATE: true,
        user_info: {
          select: {
            FIRST_NAME: true,
            LAST_NAME: true,
            EMAIL: true,
          },
        },
        info: {
          select: {
            ID_SEQ: true,
            IMEI: true,
            ENTRY_DATE: true,
            IPHONE_CARRIER: true,
            IPHONE_SIM_LOCK: true,
            APPLE_ACTIVATION_STATUS_IMEI_SN: true,
            MDM_LOCK_BYPASS_IPHONE_IPAD: true,
            ONEPLUS_INFO: true,
            MOTOROLA_INFO: true,
            GOOGLE_PIXEL_INFO: true,
            SAMSUNG_INFO: true,
            SAMSUNG_INFO_PRO: true,
            BRAND_MODEL_INFO: true,
            APPLE_SOLD_BY_COVERAGE: true,
            APPLE_IOS_VERSION_NEXT_TETHER: true,
            APPLE_PART_NUMBER_MPN: true,
            IMEI_SN_CONVERT: true,
            APPLE_SERIAL_INFO: true,
            TRACFONE_USA_STATUS_PRO: true,
            LG_INFO: true,
            ZTE_INFO: true,
            ASUS_INFO: true,
            OPPO_INFO: true,
            ACER_INFO: true,
            HONOR_INFO: true,
            DOOGEE_INFO: true,
            REALME_INFO: true,
            HUAWEI_INFO: true,
            LENOVO_INFO: true,
            KYOCERA_INFO: true,
            ALCATEL_INFO: true,
            VIVO_IQOO_INFO: true,
            NOTHING_PHONE_INFO: true,
            SIM_ICCID_IMSI_INFO: true,
            ITEL_TECNO_SONIM_INFO: true,
          },
        },
        info_delay: {
          select: {
            ID_SEQ: true,
            IMEI: true,
            ENTRY_DATE: true,
            IPHONE_CARRIER_FMI_BLACKLIST: true,
            ICLOUD_ON_OFF: true,
            APPLE_MDM_STATUS: true,
            APPLE_BASIC_INFO: true,
            WW_BLACKLIST_STATUS: true,
            USA_T_MOBILE_CLEAN: true,
            USA_AT_T_CLEAN_ACTIVE_LINE: true,
            USA_CRICKET_CLEAN_6_MONTHS_OLD: true,
            CLARO_ALL_COUNTRIES_PREMIUM_IPHONE_14: true,
            CLARO_ALL_COUNTRIES_PREMIUM_IPHONE_15: true,
            CLARO_ALL_COUNTRIES_PREMIUM_UP_TO_IPHONE_13: true,
            SAMSUNG_AT_T_CRICKET_ALL_MODELS: true,
            APPLE_GSX_CASES_REPAIRS: true,
            APPLE_GSX_CASES_ID_INFO: true,
            APPLE_GSX_POLICY_WiFi_MAC: true,
            APPLE_FULL_GSX_PREMIUM_INFO: true,
            IPHONE_CARRIER_FMI: true,
            ICLOUD_CLEAN_LOST: true,
            APPLE_MDM_ICLOUD_GSX_STATUS: true,
            MACBOOK_IMAC_ICLOUD_ON_OFF_STATUS: true,
            MACBOOK_IMAC_ICLOUD_CLEAN_LOST_STATUS: true,
            XIAOMI_MI_ACCOUNT_REMOVE_EUROPE: true,
            USA_AT_T_UNLOCK_STATUS: true,
            WW_BLACKLIST_STATUS_PRO: true,
            XFINITY_USA_STATUS_PRO: true,
            CSPIRE_USA_STATUS_PRO: true,
            MYMOBILE_USA_STATUS_PRO: true,
            CRICKET_USA_STATUS_PRO: true,
            T_MOBILE_USA_STATUS_PRO: true,
            T_MOBILE_USA_SIMLOCK_STATUS: true,
            VERIZON_USA_STATUS_PRO: true,
            KOREA_BLACKLIST_STATUS: true,
            JAPAN_BLACKLIST_STATUS: true,
            AUSTRALIA_BLACKLIST_STATUS: true,
            XIAOMI_MI_LOCK_INFO: true,
            XIAOMI_MI_LOCK_STATUS: true,
            SAMSUNG_KNOX_GUARD_INFO: true,
            UK_O2_TESCO_CLEAN: true,
            UK_VODAFONE_CLEAN: true,
            CANADA_TELUS_CLEAN: true,
            JAPAN_AU_KDDI_CLEAN: true,
            JAPAN_SOFTBANK_CLEAN: true,
            EMEA_SERVICE_PREMIUM: true,
            JAPAN_NTT_DOCOMO_CLEAN: true,
            US_RESELLER_FLEX_CLEAN: true,
            ROMANIA_ORANGE_PREMIUM: true,
            PHILIPPINES_GLOBE_CLEAN: true,
            CANADA_FIDO_ROGERS_CLEAN: true,
            ROMANIA_VODAFONE_PREMIUM: true,
            USA_AT_T_SOLD_DATE_60_DAYS: true,
            UK_EE_T_MOBILE_ORANGE_PREMIUM: true,
            HUNGARY_VODAFONE_PREMIUM_IPHONE_12_TO_14: true,
            HUNGARY_VODAFONE_PREMIUM_IPHONE_4S_TO_11: true,
            UK_O2_CLEAN: true,
            FRANCE_BOUYGUES: true,
            LG_2019_DATABASE: true,
            CANADA_VIDEOTRON: true,
            LG_2020_DATABASE: true,
            HTC_INTERNATIONAL: true,
            CANADA_BELL_NCK_CODE: true,
            SAMSUNG_EUROPE_PREMIUM: true,
            SAMSUNG_UK_IRELAND_PREMIUM: true,
            SAMSUNG_EUROPE_LIMITED_COUNTRIES: true,
          },
        },
        package_service_junction: {
          select: {
            SEQ_NUM: true,
            packages: {
              select: {
                NAME: true,
              },
            },
            services: {
              select: {
                SEQ_NUM: true,
                SERVICE: true,
                NAME: true,
              },
            },
          },
        },
      },
      orderBy: [
        { SEQ_NUM: 'desc' },
        { SERVICE_FEE: 'asc' },
      ],
    })
    
    
    return NextResponse.json(result, { status: 200 });
   }catch (error) {
      return NextResponse.json({ error }, { status: 500 });
    }
   
  }